name: appchecktest
description: A new Flutter project.

publish_to: "none"

version: 1.0.3+0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_functions: ^4.0.7
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_app_check: ^0.1.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
